package curso.java.tienda.models.entities;
// Generated 4 nov 2021 19:04:44 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MetodosPago generated by hbm2java
 */
@Entity
@Table(name = "metodos_pago", catalog = "tienda_miguel_perez_leon")
public class MetodoPago {

	private Integer id;
	private String metodoPago;

	public MetodoPago() {
	}

	public MetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "metodo_pago")
	public String getMetodoPago() {
		return this.metodoPago;
	}

	public void setMetodoPago(String metodoPago) {
		this.metodoPago = metodoPago;
	}

}
